### PR TITLE
feature/QueryBuilder

### PR DESCRIPTION
**Pull request by sensasi-delight**

### CODE REVIEW

**Comment by sensasi-delight** [comment]
jaga-jaga kalau abang males ngoding 😁
```sql
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `password` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
	(1, 'Oze1', 'oze1@oze.com', NULL),
	(2, 'Oze2', 'oze2@oze.com', NULL),
	(3, 'Oze3', 'oze3@oze.com', NULL);
```
```php
       echo '<pre>';
        // var_dump(User::select()); // error, and shouldbe
        var_dump(User::all());
        var_dump(User::select('name', 'email', 'password')->all());
        var_dump(User::select(['name', 'email', 'password'])->all());
        var_dump(User::select(['name'], 'email', 'password')->all());
        var_dump(User::select('name', ['email', 'password'])->all());
        var_dump(User::select(['name' => ['email', 'password']])->all()); // only read email and password
        echo '</pre>';
```

**Review by theozebua — COMMENTED** [review]
Ada _error_ di `Env/Environment.php`.

image

Itu untuk apa dibuat _property_-nya ya bang?

**Comment by theozebua** [comment]
> deprecation notice bang di PHP 8.2 (dynamic property)

Kita pakai PHP ^8.1 bang, lupa memang ku buat di `composer.json`
Dan aku juga udah buat `__set()` _magic method_ disitu 🤔 
Sesuai dengan dokumentasi PHP, _"The creation of dynamic properties is deprecated"_ tetapi yang menggunakan _magic method_ `__get()`/`__set()` masih tetap bisa seharusnya kalau memang abang pakainya PHP ^8.2

> The creation of dynamic properties is deprecated, unless the class opts in by using the #[\AllowDynamicProperties] attribute. [stdClass](https://www.php.net/manual/en/class.stdclass.php) allows dynamic properties. Usage of the [__get()](https://www.php.net/manual/en/language.oop5.overloading.php#object.get)/[__set()](https://www.php.net/manual/en/language.oop5.overloading.php#object.set) magic methods is not affected by this change.

[See documentation](https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties)

**Comment by sensasi-delight** [comment]
@theozebua 

> Kita pakai PHP ^8.1 bang, lupa memang ku buat di `composer.json`

udah `require php:8.1` aku masukin di https://github.com/theozebua/oze-framework-core/pull/23/commits/cab431365865173b90e190d5be575c1c9ea9080d, sudah aku *serve* di dua versi PHP gak muncul *error* bang.

> Dan aku juga udah buat `__set()` _magic method_ disitu 🤔 Sesuai dengan dokumentasi PHP, _"The creation of dynamic properties is deprecated"_ tetapi yang menggunakan _magic method_ `__get()`/`__set()` masih tetap bisa seharusnya kalau memang abang pakainya PHP ^8.2
> 
> > The creation of dynamic properties is deprecated, unless the class opts in by using the #[\AllowDynamicProperties] attribute. [stdClass](https://www.php.net/manual/en/class.stdclass.php) allows dynamic properties. Usage of the [__get()](https://www.php.net/manual/en/language.oop5.overloading.php#object.get)/[__set()](https://www.php.net/manual/en/language.oop5.overloading.php#object.set) magic methods is not affected by this change.
> 
> [See documentation](https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties)

kayaknya gini bang, `__set()` bisa tapi dynamic property di dalam `__set()` tetap bakal deprecate bang. contoh:
```php
<?php

class X
{
	private int $mililiter;

	final public function __set(string $name, mixed $value)
	{
		if ($name === 'liter') {
			$this->mililiter = $value * 1000;
		} else {
			$this->{$name} = $value;
		}
	}
}


$x = new X;

$x->liter = 2; // not dynamic 'liter' name is handled on __set()
$x->gallon = 2; // still dynamic because on it will set the `$this->gallon` dynamic prop

echo 'end program';
```

output on 8.1 and 8.2:
```bash
C:\Users\zain\Desktop\oze-framework\public>php81 test.php
end program
C:\Users\zain\Desktop\oze-framework\public>php82 test.php 

Deprecated: Creation of dynamic property X::$gallon is deprecated in C:\Users\zain\Desktop\oze-framework\public\test.php on line 12     
end program
C:\Users\zain\Desktop\oze-framework\public>
```

posible solution:
```php
<?php

class X
{
	private array $properties;

	final public function __set(string $name, mixed $value)
	{
		$this->properties[$name] = $value;
	}

	public function __get($name)
	{
		return $this->properties[$name];
	}
}


$x = new X;

$x->liter = 2;
$x->gallon = 2;

echo 'end program';
```

**Comment by theozebua** [comment]
Aku udah buat _query builder_-nya ya bang. Tinggal dilanjutkan aja, atau bisa sama-sama kita kerjakan. 😁
Silahkan ke branch [`feat/query-builder`](https://github.com/theozebua/oze-framework-core/tree/feat/query-builder).

**Pull request closed without merging**
